name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - "config/urchin.keymap"
      #- "config/*.dtsi"
      #- "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      keymap_patterns: "config/urchin.keymap"
      #config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      parse_args: ""
      draw_args: ""
